# Filename: iterate_design.toml

prompt = """

** CREATE DESIGN VARIATIONS **

UI TO BUILD: $ARGUMENTS

** GOAL ***
Your goal is to spin up 3 parallel sub agents concurrently to implement one UI
with variations,
So that users can review and decide which one is better;

** Task for each sub agent **
1. Analyse the style guide in ./gemini/design-system.json, as well as mockups for
reference
2. Build one single html page of just one screen to build a UI based on users'
feedback/task
3. Output html in ./docs/ui_iterations folder as ui_{n}.html (Where n needs to be unique
like ui_1.html, ui_2.html, etc.)

"""

description = "Creates UI iterations"
