name: Auto-Comment Java Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auto_comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Find Modified Java Files
        id: changed_files
        run: |
          PREV_COMMIT=$(git rev-parse HEAD~1 || git rev-list --max-parents=0 HEAD)
          LAST_COMMIT=$(git rev-parse HEAD)
          
          # Get list of changed Java files and replace newlines with spaces
          CHANGED_FILES=$(git diff --name-only $PREV_COMMIT $LAST_COMMIT -- '*.java' | tr '\n' ' ')
          
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No Java files changed."
            echo "changed_files=" >> $GITHUB_ENV
          else
            echo "Modified Java files: $CHANGED_FILES"
            echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
          fi

      - name: Run Auto Comment Script
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_COMMENT_TOKEN }}
        run: |
          if [[ -n "${{ env.changed_files }}" ]]; then
            # The for loop will now correctly iterate over space-separated filenames
            for file in ${{ env.changed_files }}; do
              python auto_comment.py "$file"
            done
          else
            echo "No Java files to process."
          fi

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_COMMENT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-commented Java files" || echo "No changes to commit"
          git push